services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.db-mongodb:/data/db:delegated

  example:
    build:
      context: example
      dockerfile: Dockerfile
      target: example
    volumes:
      - ./example:/example
    ports:
      - 1232:1234
    working_dir: /example
    command: npm start

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8008:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo

  student-fe:
    build:
      context: frontend/student-fe
      dockerfile: ../Dockerfile
      target: student-fe
    ports:
      - 3001:3000
    working_dir: /frontend
    command: npm start
    depends_on:
      - backend

  tutor-fe:
    build:
      context: frontend/tutor-fe
      dockerfile: ../Dockerfile
      target: tutor-fe
    ports:
      - 3002:3000
    working_dir: /frontend
    command: npm start
    depends_on:
      - backend

  faculty-fe:
    build:
      context: frontend/faculty-fe
      dockerfile: ../Dockerfile
      target: faculty-fe
    ports:
      - 3003:3000
    working_dir: /frontend
    command: npm start
    depends_on:
      - backend

  example-devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      target: example-devcontainer
    volumes:
      - .:/workspaces/little-startup
      - /home/<host-username>/.ssh:/home/little/.ssh:cached
      - /home/<host-username>/.config/nvim:/home/little/.config/nvim:cached
      - /home/<host-username>/.local/share/nvim:/home/little/.local/share/nvim:cached
      - /home/<host-username>/.local/state/nvim:/home/little/.local/state/nvim:cached
    ports:
      - 1234:1234
    environment:
      - HOST_USERNAME=<host-username>
      - UV_LINK_MODE=copy
    command: sleep infinity
    depends_on:
      - mongo

  backend-devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      target: backend-devcontainer
    volumes:
      - .:/workspaces/little-startup
      - /home/<host-username>/.ssh:/home/little/.ssh:cached
      - /home/<host-username>/.config/nvim:/home/little/.config/nvim:cached
      - /home/<host-username>/.local/share/nvim:/home/little/.local/share/nvim:cached
      - /home/<host-username>/.local/state/nvim:/home/little/.local/state/nvim:cached
    ports:
      - 8080:8080
    environment:
      - HOST_USERNAME=<host-username>
      - SPRING_PROFILES_ACTIVE=dev
    env_file: .devcontainer/backend/.env
    command: sleep infinity
    depends_on:
      - mongo

  frontend-devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      target: frontend-devcontainer
    volumes:
      - .:/workspaces/little-startup
      - /home/<host-username>/.ssh:/home/little/.ssh:cached
      - /home/<host-username>/.config/nvim:/home/little/.config/nvim:cached
      - /home/<host-username>/.local/share/nvim:/home/little/.local/share/nvim:cached
      - /home/<host-username>/.local/state/nvim:/home/little/.local/state/nvim:cached
    ports:
      - 3000:3000
    environment:
      - HOST_USERNAME=<host-username>
    command: sleep infinity
    depends_on:
      - backend
