#! /usr/bin/bash

sh initialize.sh
docker compose build --parallel

if [ $? -eq 0 ]; then
  case $1 in
    example | ex | eg)
      SERVICE='example'
      ;;
    frontend | FE | fe)
      SERVICE='frontend'
      ;;
    backend | BE | be)
      SERVICE='backend'
      ;;
    *)
      printf "Build done! Start develop your serive:\n"`
      `"  - ./nvim-start example  ( ex | eg )\n"`
      `"  - ./nvim-start backend  ( BE | be )\n"`
      `"  - ./nvim-start frontend ( FE | fe )\n"
      exit
      ;;
  esac

  docker compose up -d $SERVICE-devcontainer --remove-orphans && \
  docker exec \
    --workdir /workspaces/little-startup \
    little-startup-$SERVICE-devcontainer-1 \
    sh .devcontainer/$SERVICE/post-create.sh && \
  docker exec -it \
    --workdir /workspaces/little-startup \
    little-startup-$SERVICE-devcontainer-1 \
    nvim

  docker compose stop
else
  printf "Build failed!\n"
fi
