spring:
  application:
    name: myapp
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: file:data/
  data:
    mongodb:
      host: ${SPRING_MONGO_HOST}
      port: ${SPRING_MONGO_PORT}
      database: ${SPRING_MONGO_DB}
      username: ${SPRING_MONGO_USERNAME}
      password: ${SPRING_MONGO_PASSWORD}
      authentication-database: ${SPRING_MONGO_AUTH_DB}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    path: /api/docs/index.html

server:
  port: 8080
