spring:
    application:
        name: myapp
    data:
      mongodb:
        host: mongo
        port: 27017
        database: little_database
        username: admin
        password: admin
        authentication-database: admin
        auto-index-creation: true

springdoc:
  swagger-ui:
    path: /api/docs/index.html

server:
    port: 8080
