spring:
  config:
    import: optional:secrets.yml
  application:
    name: myapp
  data:
    mongodb:
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        transport:
          protocol: smtp

springdoc:
  swagger-ui:
    path: /api/docs/index.html

server:
  port: 8080
