spring:
    application:
        name: myapp
    data:
      mongodb:
        host: mongo
        port: 27017
        database: little_database
        username: admin
        password: admin
        authentication-database: admin
        auto-index-creation: true

    # security:
    #     user:
    #         name: admin
    #         password: admin

server:
    port: 8080
