spring:
  application:
    name: myapp
  data:
    mongodb:
      host: #{your-mongo-host}
      port: #{your-mongo-port}
      database: #{your-mongo-database}
      username: #{your-mongo-username}
      password: #{your-mongo-password}
      authentication-database: #{your-auth-db}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #{your-email}
    password: #{your-password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    path: /api/docs/index.html

server:
  port: 8080
