spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: little_database
      username: admin
      password: admin
      authentication-database: admin
  mail:
    username:
    password:
