name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-docker-action@v4.3.0
      - run: bash ops.sh test
      # - run: bash ops.sh start
